### ISSUE TITLE
但凡给OpenHarmony生态添砖加瓦的行为都是糟蹋。开源软件精神，自由软件精神乃至最基本的用户隐私权的精神

### ISSUE THREAD

**Issue by ghost** [Wscats/openharmony-sheet#3]

**Comment by frederick-vs-ja** [comment]
你有啥精神？

**Comment by Licshee** [comment]
> 你有啥精神？

拥护他白皮偶像主动把政治带进FOSS社区破坏生态的精神。

**Comment by frederick-vs-ja** [comment]
> > 你有啥精神？
> 
> 拥护他白皮偶像主动把政治带进FOSS社区破坏生态的精神。

挺奇怪的，除了国籍以外 Linus 这次表现得和所谓的粉红真得很相似。

**Comment by Licshee** [comment]
> > > 你有啥精神？
> > 
> > 
> > 拥护他白皮偶像主动把政治带进FOSS社区破坏生态的精神。
> 
> 挺奇怪的，除了国籍以外 Linus 这次表现得和所谓的粉红真得很相似。

抛开屁股不谈，这就是在没有强制力干预下野蛮生长出来的纯天然民族主义本来会有的样子。
