### ISSUE TITLE
OpenHarmony 是开源软件，尊重用户隐私，给 OpenHarmony 生态添砖加瓦是尊重开源精神和用户隐私权的行为。

### ISSUE THREAD

**Issue by tyhjtoo** [Wscats/openharmony-sheet#4]
OpenHarmony 是开源软件，尊重用户隐私，给 OpenHarmony 生态添砖加瓦是尊重开源精神和用户隐私权的行为。

**Comment by ghost** [comment]
赛里斯程序员是丝毫不知道，他们自己是在上面眼中需要重点打击的对象，帮着利维坦的东西说话。还真tm以为自己跟上面是一伙了的是吧，看清楚自己在上面眼中是什么样的人，鸿蒙禁止侧载这种操作你跟我说，不违反自由软件的原则，笑死。

**Comment by ghost** [comment]
> OpenHarmony 是开源软件，尊重用户隐私，给 OpenHarmony 生态添砖加瓦是尊重开源精神和用户隐私权的行为。

所有品客程序员都将迎来他们最喜爱的承德警方。
