### ISSUE TITLE
去你m的吧

### ISSUE THREAD

**Issue by ghost** [Wscats/openharmony-sheet#5]
搞开源的应该清楚自己是个什么成分，真以为开源是纯粹不沾政治的吗。哈哈，开源这个概念本质上是赛里斯宣传中的所谓西方体系下的一种产物，根本不是所谓的纯净技术东西。一边骂着西方殖民历史又鼓吹开源，这就是你们这帮品客程序员的德性。程序员当什么兔兔嘛。

**Comment by frederick-vs-ja** [comment]
你理解不了开源可以不说话。

**Comment by Licshee** [comment]
> 搞开源的应该清楚自己是个什么成分，真以为开源是纯粹不沾政治的吗。哈哈，开源这个概念本质上是赛里斯宣传中的所谓西方体系下的一种产物，根本不是所谓的纯净技术东西。一边骂着西方殖民历史又鼓吹开源，这就是你们这帮品客程序员的德性。程序员当什么兔兔嘛。

https://moglen.law.columbia.edu/publications/dcm.html
