### ISSUE TITLE
赛里斯程序员真的有很多粉红逼的，丝毫不知道开源这个事情，对利维坦是属于跟业余无线电一样不可控需要控制的。

### ISSUE THREAD

**Issue by ghost** [Wscats/openharmony-sheet#6]
创造性的事物是必须要被商业化，必须要被利维坦以各种方式控制的。中国开源最大的敌人就是政府。

**Comment by ghost** [comment]
搞开源还所谓爱国，有一种孩子觉得父母需要什么，想要回报父母，然后孩子给父母闯祸的感觉。

**Comment by liungkejin** [comment]
你看有人理你吗？小丑！你以为你喷两句就能改变什么？不喜欢就别看啊！不喜欢还要恶心自己就是贱！

**Comment by frederick-vs-ja** [comment]
惊了，开源社区和政府从未表示过这种敌对关系。

**Comment by ghost** [comment]
> 惊了，开源社区和政府从未表示过这种敌对关系。

在西方国家确实不敌对，可是这个项目的作者还有参与讨论的人很明显是在东方国家。

**Comment by frederick-vs-ja** [comment]
> > 惊了，开源社区和政府从未表示过这种敌对关系。
> 
> 在西方国家确实不敌对，可是这个项目的作者还有参与讨论的人很明显是在东方国家。

东方国家也不敌对。你想意淫脑补可以写小说，不要把这种东西套在真实群体上。

**Comment by ghost** [comment]
> > > 惊了，开源社区和政府从未表示过这种敌对关系。
> > 
> > 在西方国家确实不敌对，可是这个项目的作者还有参与讨论的人很明显是在东方国家。
> 
> 东方国家也不敌对。你想意淫脑补可以写小说，不要把这种东西套在真实群体上。

一个自由的、隐私的系统，墙和维稳还搞个毛线。

**Comment by frederick-vs-ja** [comment]
> > > > 惊了，开源社区和政府从未表示过这种敌对关系。
> > > 
> > > 
> > > 在西方国家确实不敌对，可是这个项目的作者还有参与讨论的人很明显是在东方国家。
> > 
> > 
> > 东方国家也不敌对。你想意淫脑补可以写小说，不要把这种东西套在真实群体上。
> 
> 一个自由的、隐私的系统，墙和维稳还搞个毛线。

你怎么似了？斯诺登认识不？美国搞那套下来不照样和开源兼容得好好的？
